@startmindmap
<style>
:depth(0) {
    BackgroundColor #091f2c
    FontColor #ffffff
    LineThickness 3.0
}
.topic1 {
    BackgroundColor #ffb900
    LineColor #ffb900
    LineThickness 3.0
    FontColor #000000
}
.topic2 {
    BackgroundColor #f4364c
    LineColor #f4364c
    LineThickness 3.0
    FontColor #ffffff
}
.topic3 {
    BackgroundColor #c5b4e3
    LineColor #c5b4e3
    LineThickness 3.0
    FontColor #000000
}
.topic4 {
    BackgroundColor #e1d3c7
    LineColor #e1d3c7
    LineThickness 3.0
    FontColor #000000
}
.topic5 {
    BackgroundColor #07641d
    LineColor #07641d
    LineThickness 3.0
    FontColor #ffffff
}
</style>
+ Data engineering on Azure
++ 1) What is data engineering <<topic1>>
+++ Types of data <<topic1>>
++++_ Structured
++++_ Unstructured
++++_ Semi-Structured
+++ Data operations <<topic1>>
++++_ Data integration
++++_ Data transformation
++++_ Data consolidation
+++ Common languages <<topic1>>
++++_ SQL
++++_ Python
++++_ Others: R, Java, Scala, .NET, ...
++ 2) Important data engineering concepts <<topic2>>
+++_ Operational and analytical data
+++_ Streaming data
+++_ Data pipelines
+++_ Data lakes
+++_ Data warehouses
+++_ Apache Spark
++ 3) Data engineering in Microsoft Azure <<topic3>>
+++_ Azure Synapse Analytics
+++_ Azure Data Lake Storage Gen2
+++_ Azure Stream Analytics
+++_ Azure Data Factory
+++_ Azure Databricks
@endmindmap