@startmindmap
<style>

:depth(0) {
    BackgroundColor #091f2c
    FontColor #ffffff
    LineThickness 3.0
}
.topic1 {
    BackgroundColor #ffb900
    LineColor #ffb900
    LineThickness 3.0
    FontColor #000000
}
.topic2 {
    BackgroundColor #f4364c
    LineColor #f4364c
    LineThickness 3.0
    FontColor #ffffff
}
.topic3 {
    BackgroundColor #c5b4e3
    LineColor #c5b4e3
    LineThickness 3.0
    FontColor #000000
}
.topic4 {
    BackgroundColor #e1d3c7
    LineColor #e1d3c7
    LineThickness 3.0
    FontColor #000000
}
.topic5 {
    BackgroundColor #07641d
    LineColor #07641d
    LineThickness 3.0
    FontColor #ffffff
}
</style>
+ Azure Data Lake Storage Gen2
-- 1) Understand Azure Data Lake Storage Gen2 <<topic1>>
--- What is it <<topic1>>
----_ File system, storage platform for analytics workloads
--- Benefits <<topic1>>
----_ Hadoop compatible access (Databricks, HDInsight, Synapse Analytics)
----_ Security (ACLs)
----_ Performance (folders, subfolders)
----_ Data redundancy (LRS, GRS)
--- Governance required <<topic1>>
----_ Types of data to be stored
----_ How the data will be transformed
----_ Who should access the data
----_ What are the typical access patterns
----_ Data residency
-- 2) How to enable ADLS gen2? <<topic2>>
--- Enable hierarchical namespace <<topic2>>
--- Data Lake Gen2 upgrade <<topic2>>
-- 3) Compare ADLS to Blob storage <<topic3>>
--- Flat namespace versus Hierarchical namespace <<topic3>>
--- Pricing differences <<topic3>>
++ 4) Stages for processing big data <<topic4>>
+++ 1. Ingest <<topic4>>
++++_ Synapse Pipelines, Azure Data Factory, Kafka, Stream Analytics
+++ 2. Store <<topic4>>
++++_ Data Lake Storage Gen2
+++ 3. Prep and train <<topic4>>
++++_ Synapse Analytics, Databricks, HDInsight, Azure Machine Learning
+++ 4. Model and serve <<topic4>>
++++_ Power BI, Synapse Analytics
++ 5) Data analytics workloads <<topic5>>
+++ Big data processing and analytics <<topic5>>
++++_ Volume, variety, velocity
++++_ Distributed storage and processing, parallel execution
+++ Data warehousing <<topic5>>
++++_ Data lake as staging, before loading into DWH
++++_ DWH External tables (metadata layer over files in datalake)
++++_ Data lakehouse or lake database
+++ Real-time data analytics <<topic5>>
++++_ Devices, Social media, Applications, ...
++++_ Azure Stream Analytics output to ADLS
+++ Data science and machine learning <<topic5>>
++++_ Azure Machine Learning
@endmindmap