@startmindmap
<style>
:depth(0) {
    BackgroundColor #091f2c
    FontColor #ffffff
    LineThickness 3.0
}
.topic1 {
    BackgroundColor #ffb900
    LineColor #ffb900
    LineThickness 3.0
    FontColor #000000
}
.topic2 {
    BackgroundColor #f4364c
    LineColor #f4364c
    LineThickness 3.0
    FontColor #ffffff
}
.topic3 {
    BackgroundColor #c5b4e3
    LineColor #c5b4e3
    LineThickness 3.0
    FontColor #000000
}
.topic4 {
    BackgroundColor #e1d3c7
    LineColor #e1d3c7
    LineThickness 3.0
    FontColor #000000
}
.topic5 {
    BackgroundColor #07641d
    LineColor #07641d
    LineThickness 3.0
    FontColor #ffffff
}
</style>
+ Azure Synapse Analytics
++ 1) Types of analytics <<topic1>>
+++_ Descriptive analytics
+++_ Diagnostic analytics
+++_ Predictive analytics
+++_ Prescriptive analytics
++ 3) When to use it? <<topic3>>
+++_ Large-scale data warehousing
+++_ Advanced analytics
+++_ Data exploration and discovery
+++_ Real time analytics
+++_ Data integration
+++_ Integrated analytics
++ 2) How does it work <<topic2>>
+++_ Creating and using an Azure Synapse Analytics workspace
+++_ Working with files in a data lake
+++_ Ingesting and transforming data with pipelines
+++_ Querying and manipulating data with SQL
++++_ A built-in serverless pool
++++_ Custom dedicated SQL pools
+++_ Processing and analyzing data with Apache Spark
+++_ Exploring data with Data Explorer
+++_ Integrating with other Azure data services
++++_ Azure Synapse Link
++++_ Power BI
++++_ Microsoft Purview
++++_ Azure Machine Learning
@endmindmap