@startmindmap
<style>
:depth(0) {
    BackgroundColor #091f2c
    FontColor #ffffff
    LineThickness 3.0
}
.topic1 {
    BackgroundColor #ffb900
    LineColor #ffb900
    LineThickness 3.0
    FontColor #000000
}
.topic2 {
    BackgroundColor #f4364c
    LineColor #f4364c
    LineThickness 3.0
    FontColor #ffffff
}
.topic3 {
    BackgroundColor #c5b4e3
    LineColor #c5b4e3
    LineThickness 3.0
    FontColor #000000
}
.topic4 {
    BackgroundColor #e1d3c7
    LineColor #e1d3c7
    LineThickness 3.0
    FontColor #000000
}
.topic5 {
    BackgroundColor #07641d
    LineColor #07641d
    LineThickness 3.0
    FontColor #ffffff
}
</style>
+ Lake databases
-- 1) Concepts <<topic1>>
---_ Relational metadata layer over files in a data lake
---_ Data is stored in files (csv, json, parquet, ...)
---_ Query it using SQL (T-SQL in Serverless Pools or Spark SQL API)
-- 2) Database templates <<topic2>>
---_ Common schemas found in multiple business scenarios
---_ Starting point for creating a lake database
++ 3) How to create? <<topic3>>
+++_ Database designer
+++_ Table storage settings
+++_ Field names, key usage, nullability, and data types
+++_ Relationships between key columns in tables
++ 4) How to use? <<topic4>>
+++_ Use serverless SQL pool
+++_ Use Apache Spark pool
@endmindmap