@startmindmap
<style>
:depth(0) {
    BackgroundColor #091f2c
    FontColor #ffffff
    LineThickness 3.0
}
.topic1 {
    BackgroundColor #ffb900
    LineColor #ffb900
    LineThickness 3.0
    FontColor #000000
}
.topic2 {
    BackgroundColor #f4364c
    LineColor #f4364c
    LineThickness 3.0
    FontColor #ffffff
}
.topic3 {
    BackgroundColor #c5b4e3
    LineColor #c5b4e3
    LineThickness 3.0
    FontColor #000000
}
.topic4 {
    BackgroundColor #e1d3c7
    LineColor #e1d3c7
    LineThickness 3.0
    FontColor #000000
}
.topic5 {
    BackgroundColor #07641d
    LineColor #07641d
    LineThickness 3.0
    FontColor #ffffff
}
</style>
+ Azure Databricks
++ 1) Get started with Azure Databricks <<topic1>>
+++_ Create an Azure Databricks workspace
+++ Pricing tiers <<topic1>>
++++_ Standard (Azure AD integration)
++++_ Premium (Role-based access control + Enterprise-level features)
++++_ Trial (14-day free trial)
+++_ Use the Azure Databricks portal
++ 2) Identify Azure Databricks workloads <<topic2>>
+++_ Data Science and Engineering
+++_ Machine Learning
+++_ SQL Warehouse (Premium)
++ 3) Understand key concepts <<topic3>>
+++_ Apache Spark Clusters
+++_ Databricks File System DBFS (mount storage)
+++_ Notebooks
+++_ Hive metastore
+++_ Delta Lake
+++_ SQL Warehouse (Premium)
@endmindmap