@startmindmap
<style>
:depth(0) {
    BackgroundColor #091f2c
    FontColor #ffffff
    LineThickness 3.0
}
.topic1 {
    BackgroundColor #ffb900
    LineColor #ffb900
    LineThickness 3.0
    FontColor #000000
}
.topic2 {
    BackgroundColor #f4364c
    LineColor #f4364c
    LineThickness 3.0
    FontColor #ffffff
}
.topic3 {
    BackgroundColor #c5b4e3
    LineColor #c5b4e3
    LineThickness 3.0
    FontColor #000000
}
.topic4 {
    BackgroundColor #e1d3c7
    LineColor #e1d3c7
    LineThickness 3.0
    FontColor #000000
}
.topic5 {
    BackgroundColor #07641d
    LineColor #07641d
    LineThickness 3.0
    FontColor #ffffff
}
</style>
+ Start
++ 1) Understand Azure Databricks notebooks and pipelines <<topic1>>
++ 2) Create a linked service for Azure Databricks <<topic2>>
+++_ Generate an access token
+++_ Create a linked service
++ 3) Use a Notebook activity in a pipeline <<topic3>>
++ 4) Use parameters in a notebook <<topic4>>
+++_ dbutils.widgets.get()
+++_ dbutils.notebook.exit()
+++_ Set parameter values in a pipeline
@endmindmap